### ISSUE TITLE
ClassNotFoundException on server start-up

### ISSUE THREAD

**Issue by SlimeDog** [stijnb1234/V10Lift2#54]
**Describe the bug**
ClassNotFoundException on server start-up

**To Reproduce**
1. Upgrade to V10Lift 0.7 from 0.6
2. Start server
3. See error

**Java version (use /version):** 11.0.4
**Spigot version (use /version):** 1.16.3
**Plugin version (use /v10lift info), NOT LATEST!!!** 0.7

**Log**
```
[09:34:57] [Server thread/ERROR]: Could not load 'plugins/V10Lift-0.7.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class `nl.SBDeveloper.v10lift.V10LiftPlugin'
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:66) ~[spigot-1.16.3.jar-2020-09-19-0406:git-Spigot-17d78db-f8d4da0]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.16.3.jar-2020-09-19-0406:git-Spigot-17d78db-f8d4da0]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-1.16.3.jar-2020-09-19-0406:git-Spigot-17d78db-f8d4da0]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-1.16.3.jar-2020-09-19-0406:git-Spigot-17d78db-f8d4da0]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.loadPlugins(CraftServer.java:383) ~[spigot-1.16.3.jar-2020-09-19-0406:git-Spigot-17d78db-f8d4da0]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:183) ~[spigot-1.16.3.jar-2020-09-19-0406:git-Spigot-17d78db-f8d4da0]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:808) ~[spigot-1.16.3.jar-2020-09-19-0406:git-Spigot-17d78db-f8d4da0]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar-2020-09-19-0406:git-Spigot-17d78db-f8d4da0]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: nl.SBDeveloper.v10lift.V10LiftPlugin
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.16.3.jar-2020-09-19-0406:git-Spigot-17d78db-f8d4da0]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.3.jar-2020-09-19-0406:git-Spigot-17d78db-f8d4da0]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot-1.16.3.jar-2020-09-19-0406:git-Spigot-17d78db-f8d4da0]
        ... 8 more
```

**Comment by SlimeDog** [comment]
Fixed if V10Lift 0.7.1
Rudimentary pre-release testing:
- Loads without error, upgrading from the previous release
- Loads without error, on a clean install
- Moves a canonical (test) elevator
